version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=blogdata
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/volume/blogmysql:/var/lib/mysql

  web:
    build: .
    command: /bin/bash
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
